# Generated by Django 3.1.5 on 2021-05-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SectionS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=150)),
                ('Dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.departmentd')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fullname')),
                ('Mobile', models.CharField(blank=True, max_length=150, null=True, verbose_name=' Mobile')),
                ('Address', models.CharField(blank=True, max_length=150, null=True, verbose_name=' Mobile')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Images')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('DepNameD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.departmentd', verbose_name='Department')),
                ('secS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acc.sections', verbose_name='section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
