# Generated by Django 3.1.5 on 2021-05-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DepNameD',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acc.departmentd', verbose_name='Department'),
        ),
    ]
