# Generated by Django 3.1.5 on 2021-05-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sec',
            name='user',
        ),
    ]
