# Generated by Django 3.1.5 on 2021-05-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20210523_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userType',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('User', 'User')], default='User', max_length=150),
        ),
    ]
