# Generated by Django 3.1.5 on 2021-05-21 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_auto_20210521_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dep',
            name='secN',
        ),
        migrations.AddField(
            model_name='sec',
            name='Dep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acc.dep'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='DepN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DepN_set', to='acc.sec'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secN_set', to='acc.sec'),
        ),
    ]
